/* This file is autogenerated by generate-buildinfo.sh */

#ifndef _EXAHYPE_BUILD_INFO_H_
#define _EXAHYPE_BUILD_INFO_H_

#define EXAHYPE_BUILDINFO_AVAILABLE
#define EXAHYPE_BUILD_DATE          "Sat Apr 3 14:04:10 UTC 2021"
#define EXAHYPE_BUILD_HOST          "f0672cb186b4"

/* Strings passed by the Makefile */
#define EXAHYPE_BUILD_INFO \
    "COMPILER = GNU\n" \
    "MODE = Release\n" \
    "SHAREDMEM = TBB\n" \
    "DISTRIBUTEDMEM = MPI\n" \
    "------\n" \
    "ARCHITECTURE = snb\n" \
    "CC = mpicc\n" \
    "BOUNDARYCONDITIONS = None\n" \
    "------\n" \
    "COMPILER_CFLAGS =  -I/dependencies/easi/include/ -DTrackGridStatistics -std=c++11 -pedantic -Wall -Drestrict=__restrict__ -pipe -D__assume_aligned=__builtin_assume_aligned -Wstrict-aliasing -fopenmp-simd -O3  -march=sandybridge -DSharedTBB -DParallel -DnoPackedRecords -DnoPersistentRegularSubtrees  -DIprobeEveryKIterations=0 -DUsePeanosRLEBoundaryExchanger -DUsePeanosRLEBoundaryExchangerForMetaData\n" \
    "COMPILER_LFLAGS =   -L/dependencies/easi/build/ -leasi -L/dependencies/ImpalaJIT/build/ -limpalajit -L/usr/lib/x86_64-linux-gnu/ -lyaml-cpp  -L/dependencies/ASAGI/ -lasagi -lpthread -lm -lstdc++ -march=sandybridge\n" \
    "FCOMPILER_CFLAGS = -fdefault-real-8 -fdefault-double-8 -ffree-line-length-none -cpp -Wall -Wno-tabs -Wno-unused-variable -fopenmp-simd -O3 \n" \
    "FCOMPILER_LFLAGS = \n" \
    "------\n" \
    "EXAHYPE_PATH = /ExaHyPE-Tsunami/ExaHyPE\n" \
    "PROJECT_PATH = /ExaHyPE-Tsunami/ApplicationExamples/SWE/SWE_asagi_limited\n" \
    "PEANO_KERNEL_PEANO_PATH = /ExaHyPE-Tsunami/Peano/peano\n" \
    "PEANO_KERNEL_TARCH_PATH = /ExaHyPE-Tsunami/Peano/tarch\n" \
    "------\n" \
    "PROJECT_CFLAGS = -DUSE_ASAGI -DDim2 -DALIGNMENT=32\n" \
    "PROJECT_LFLAGS = \n" \
    ""


/*
 * ExaHyPE Git Repository information extraction
 * Extracted from git repository in /ExaHyPE-Tsunami/ExaHyPE
 */

/* Information collected with git version 2.25.1 */
#define EXAHYPE_GIT_INFO "master  4e40ffb Fri Apr 2 08:09:11 2021"

/*
 * Peano Git Repository information extraction
 * Extracted from git repository in /ExaHyPE-Tsunami/Peano/peano
 */

/* Information collected with git version 2.25.1 */
#define PEANO_GIT_INFO "master  4e40ffb Fri Apr 2 08:09:11 2021"
#define PEANO_SVN_INFO  PEANO_GIT_INFO /* transition time */

/*
    Peano version check

    FIXME TODO This is the worst place ever to hook in version
               requirements. Please move the following to somewhere
               suitable, such as the Peano startup phase.

*/

#include "peano/version.h"

#endif /* EXAHYPE_BUILD_INFO_H */
#if PEANO_VERSION<2509 
#error Old Peano version. Version 2509 required. Please update your Peano installation.
#endif
